### ISSUE TITLE
RFC: 添加赞助商的logo

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#104]
我们目前JuliaCN的主要几个面向大众的项目都没有给目前主要的赞助商（集智俱乐部）打LOGO，目前其实每年的服务器开销和宣传上的一些帮助都是他们在帮忙。我觉得我们可以考虑在文档和新的中文社区首页里致谢一下？

**Comment by inkydragon** [comment]
最简单的是把 footer 的
> 感谢 Fastly 慷慨的基础设施支持。
给改了。

如果想新开一节做介绍，给个布局我试着做一下看看效果。
简单一点就像 “语言生态” 中的一小节一样，一张图（logo）+ 一段文字介绍。

文档就新开一个 md 吧，应该是会自动加一小节的。

**Comment by Roger-luo** [comment]
目前主要是集智俱乐部，他们的logo在这里

![](https://swarma.org/wp-content/uploads/2018/08/logochange_副本2.png)

文档我们加载首页的index里如何？加一个小的section。

**Comment by Roger-luo** [comment]
> 最简单的是把 footer 的

嗯，我觉得我们主页就改一下footer吧。我提PR吧。
