### ISSUE TITLE
Build文档失败

### ISSUE THREAD

**Issue by kands-code** [JuliaCN/JuliaZH.jl#115]
我尝试去build文档结果出现以下报错
![图片](https://user-images.githubusercontent.com/59006329/102103979-9d35c600-3e68-11eb-9d4a-4d9ca1d16eb1.png)

很明显,不是我没有ctex套件，而是这个链接有问题，我尝试直接访问，却发现这个链接是无效的

**Comment by Roger-luo** [comment]
刚刚再次确认了一下，链接是有效的。你在build的时候有翻墙吗？很有可能是被墙了。
