### ISSUE TITLE
请更新master分支为main，部署到一些服务器，如deepnote，不会自动初始化master分支

### ISSUE THREAD

**Issue by aifact** [JuliaCN/JuliaZH.jl#131]
deepnote
![image](https://user-images.githubusercontent.com/79238945/146344859-7f0d2cc7-15d5-4165-92f9-993fea85ad9b.png)

https://stackoverflow.com/questions/4181861/git-message-src-refspec-master-does-not-match-any-when-pushing-commits-in-git

**Comment by johnnychen94** [comment]
这个看起来应该是具体部署方面的问题：在使用时不应该对默认分支的名称有任何假设才是。
