### ISSUE TITLE
境内文档服务器同步

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#16]
现在文档在hexo生成的静态文件 `public` 下的 `docs`里

- [x] 文档同步脚本
- [x] 子域名：`docs.juliacn.com`

**Comment by findmyway** [comment]
1. 我一直在用[Git-Auto-Deploy](https://github.com/olipo186/Git-Auto-Deploy)，感觉还很方便，只需要配置下webhook，端口就行
2. 为了与docs.juliacn.com打通，需要更新下`docs/make.jl`下的`makedocs`中的`html_canonical`字段？这样，配合1中的webhook，可以实现自动同步

**Comment by findmyway** [comment]
目前的pipeline是：

1. master更新
1. 触发Travis，测试
1. Documenter.jl build 文档，推送到gh-pages分支
1. 触发webhook，发送事件给境内服务器上的Git-Auto-Deploy (通过suprevisor监听，挂了后自动重启)
1. 执行git pull逻辑，更新文档
1. 用户请求docs.juliacn.com，nginx重定向到latest目录下
