### ISSUE TITLE
使用transifex的翻译平台辅助翻译

### ISSUE THREAD

**Issue by Gnimuc** [JuliaCN/JuliaZH.jl#18]
试用了一下[transifex](www.transifex.com)，支持主流的localization文件格式以及Markdown，它的优点是支持自动同步和merge等功能，翻译者只需要关心翻译的内容，无需走复杂的Github Flow。我建了一个测试的project: https://www.transifex.com/juliacn/  大家可以测试一下。一个明显的缺点是国内访问起来有点卡。

**Comment by Roger-luo** [comment]
这个平台之前翻译西班牙语的人用过，问题是怎么host在国内？现在应该都是静态网页可以直接host在国内。再一个就是标准库和其它二进制文档怎么处理？

**Comment by Gnimuc** [comment]
host还是和目前一样，transifex有客户端，可以把transifex上project翻译好的文档同步到本地，再用git push到JuliaZH就可以了。区别是翻译者只通过transifex做翻译工作，不直接向JuliaZH.jl commit。维护者定期从transifex同步。

**Comment by Gnimuc** [comment]
二进制文档是指docstrings吗？https://github.com/Roger-luo/Localize.jl/issues/7

**Comment by Roger-luo** [comment]
OK, 那就需要Localize提供dump到对应文件的功能？

**Comment by Roger-luo** [comment]
transifex 能track是谁写的翻译么？我没找到。如果不行的话，需要让大家还是回到那个issue下comment一下，不然以后文档翻译的致谢没法写了。

**Comment by Gnimuc** [comment]
@Roger-luo 那要看需要追溯到多具体了，transifex每个词条都有谁更改的历史记录，我感觉致谢写的general一些就好，贡献者链接指向transifex，贡献突出的special thanks说一下。

**Comment by Gnimuc** [comment]
现在翻译进度比较低，所以没开放审阅权限，以后真正有贡献或帮忙维护的给审阅或维护权限，然后整个文档就完全社区驱动了。

**Comment by Roger-luo** [comment]
OK，我找到怎么track了。然后其实过去的一些文档也依然可以再利用起来的。可以搬运顺便审校。我之后重新写一下手册翻译列表的issue。

**Comment by Gnimuc** [comment]
@Roger-luo  前两天我已经搬运了一些了，string和parallel computing还没搬。能否在论坛上开一个文档翻译分类(可以置顶一些帖子)，我发现文档翻译以及审阅需要讨论的问题还挺多的，我一会把最近transifex平台看到的问题总结一下，写一个翻译指南。

**Comment by Roger-luo** [comment]
好了 @Gnimuc 新增了*中文文档* 分类。http://discourse.juliacn.com/t/topic/268

**Comment by Gnimuc** [comment]
翻译指南: http://discourse.juliacn.com/t/topic/277
