### ISSUE TITLE
建一个JuliaCN专用bot账号来自动同步transifex

### ISSUE THREAD

**Issue by Gnimuc** [JuliaCN/JuliaZH.jl#23]
似乎可以用Travis CI的定期构建功能来同步transifex，用GitHub token自动push到transifex 分支。

**Comment by findmyway** [comment]
我没用过bot，不过似乎只要能像Documenter一样能push就行？

**Comment by Roger-luo** [comment]
不用bot吧，可能怎么配置一下travis就可以自动pull然后push到这边的master？

**Comment by lowrank** [comment]
> 不用bot吧，可能怎么配置一下travis就可以自动pull然后push到这边的master？

https://docs.travis-ci.com/user/cron-jobs/

**Comment by Gnimuc** [comment]
由于 Transifex 对于 markdown 的解析有 bug，有些 diff 仍需要人工审核。
