### ISSUE TITLE
I can not add JuliaZH in Julia 1.0.0 with the following errors.

### ISSUE THREAD

**Issue by askuyue** [JuliaCN/JuliaZH.jl#30]
(v1.0) pkg> add JuliaZH
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * JuliaZH (not found in project, manifest or registry)
Please specify by known `name=uuid`.

**Comment by Roger-luo** [comment]
Please read the README.
