### ISSUE TITLE
using JuliaZH doesn't replace kw_str doc

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#41]
I posted a MWE on discourse: https://discourse.julialang.org/t/cannot-replace-doctoring-in-projects/15805

**Comment by ViralBShah** [comment]
Probably should go upstream to make translations first class.

**Comment by Gnimuc** [comment]
It would be great if we could either use or emulate GNU gettext in Julia.

**Comment by Roger-luo** [comment]
Yeah, but I think this is some issue related to some commit in **0.7**, it worked in 0.7 for some period.

**Comment by inkydragon** [comment]
> use or emulate GNU gettext in Julia.

- [Julia-i18n/Gettext.jl: i18n for Julia](https://github.com/Julia-i18n/Gettext.jl)
> Currently this library relies on Python's built-in gettext.py implementation via PyCall.
> In the future, it may make sense to port this code into a Julia-native version (see [Issue #1](https://github.com/Julia-i18n/Gettext.jl/issues/1)).

**Comment by Gnimuc** [comment]
I guess the problem is no one would like to invest time to make this happen for now. Emulating gettext in Julia needs to hack into the Julia compiler, the first step is writing a Julep proposal. But the good news is we only need a PO file parser for supporting docstring substitution.

**Comment by Roger-luo** [comment]
Yeah, agree with @Gnimuc I believe for most people after reading manual, they will be able to use most of the functionality and who is interested in development usually has the ability on reading English. We haven't had a large user group that requires such localization yet. 

Other package/functionality can be in higher priority, so people have to work on other things first. Like me, my job queue is totally full for the next 4 month… So I would say we should wait for a while on this, and focus on manual first. 

And on the other side, machine translation algorithm is growing fast, my friends are working on something related, they can analysis HTML directly (https://fanyi.caiyunapp.com). so I'm wondering if it's possible to integrate their application or things like Google translate directly. Then even new package developed in Julia will get i18n support. 

I just asked their CTO about this. I'll update here if we get any further idea.

But again, I guess this won't influence much on the user experience. So not as urgent as manual part.

**Comment by Roger-luo** [comment]
And the point for the original issue is that the doc string for keywords is not working after 1.0. it's definitely some kind of bug. Nothing related to gettext in this part.
