### ISSUE TITLE
替换MIT License为 CC BY-NC-SA 4.0?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#45]
这个repo不是一个代码repo，使用这个协议应该更合适一些？

**Comment by findmyway** [comment]
感觉可以详细声明下：

比如像这里这样：

https://github.com/github/choosealicense.com#license

> The content of this project itself is licensed under the Creative Commons Attribution 3.0 Unported license, and the underlying source code used to format and display that content is licensed under the MIT license.

Julia文档的主站并没有这样声明，不过考虑到国情，我倾向于增加 CC BY-NC-SA 4.0
