### ISSUE TITLE
损坏的链接

### ISSUE THREAD

**Issue by inkydragon** [JuliaCN/JuliaZH.jl#47]
[主页 · Julia中文文档](https://juliacn.gitlab.io/JuliaZH.jl/) 右上的 `Edit on GitHub` 链接有问题，整个文档都有问题。

```
https://github.com//blob/master/doc/src/index.md
```

----

翻 `Documenter.jl` 的源码。链接是这样拼接的
> `"https://github.com/$remote/blob/{commit}{path}#{line}"`
> ——  [Documenter.jl/Utilities.jl at master · JuliaDocs/Documenter.jl](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Utilities/Utilities.jl#L435)

`$remote` 通过 `getremote()` 获得

> ```
> function getremote(dir::AbstractString)
>     remote =
>         try
>             cd(() -> readchomp(`git config --get remote.origin.url`), dir)
>         catch err
>             ""
>         end
>     m = match(LibGit2.GITHUB_REGEX, remote)
>     if m === nothing
>         travis = get(ENV, "TRAVIS_REPO_SLUG", "")
>         isempty(travis) ? "" : travis
>     else
>         m[1]
>     end
> end
> ```
> —— [Documenter.jl/Utilities.jl at master · JuliaDocs/Documenter.jl](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Utilities/Utilities.jl#L449-L463)

可能是编译环境里没 git？还是权限不够?看上去 `.travis` 设置个 `TRAVIS_REPO_SLUG` 可以强行解决这个问题。

**Comment by inkydragon** [comment]
顺便吐槽下垃圾 github： [GitHub 新支持在 issue 插入代码段](http://top.jobbole.com/37409/) 这个玩意跨 repo 就不能用了。

repo 内链就是好的。效果如下：
`https://github.com/JuliaCN/JuliaZH.jl/blob/2176cbed3c5590213085ed32aa0fe8d522c9bf07/.codecov.yml#L1`
会变成
https://github.com/JuliaCN/JuliaZH.jl/blob/2176cbed3c5590213085ed32aa0fe8d522c9bf07/.codecov.yml#L1

跨 repo 就不行：
https://github.com/JuliaLang/julia/blob/534fe442d41fb55749a12444ae6f38970c2dfb59/.travis.yml#L127

**Comment by Roger-luo** [comment]
@Gnimuc 我们现在的Documenter似乎是在gitlab上？然后导致找不到repo地址？

**Comment by Gnimuc** [comment]
如果都在 Transifex 上维护文档的话，这里其实应该删除 `Edit on GitHub`, 否则会诱导更多的人直接点进 repo 修改。

**Comment by inkydragon** [comment]
那就直接删掉？`Documenter.jl` 里没找到关闭这个的选项，应该需要魔改一下，或者在生成完 HTML 之后再把这部分删掉。看上去魔改更简单一点。

魔改还可以考虑吧连接改成 transfix 的，
`https://www.transifex.com/juliacn/manual-zh_cn/translate/#zh_CN/arraysmd/`
没登录会让你去登录，已经登陆的会打开对应的翻译界面，没加入项目组的没有测试过。

**Comment by Gnimuc** [comment]
可以参考一下韩国人这个 https://github.com/juliakorea/translate-doc/blob/master/contrib/html_writer.jl 把翻页也改了。

**Comment by inkydragon** [comment]
> 可以参考一下韩国人这个 https://github.com/juliakorea/translate-doc/blob/master/contrib/html_writer.jl 把翻页也改了。

[Diff 了一下](https://www.diffchecker.com/ESAkRnlY) 韩国人改了这些东西：
1. 导入需要的函数
2. 改 `render_head()` 
    - @tag 加了 style
    - 删了 `canonical_link_element()`
    - 加了 `custom.css`
    - 加了韩语分词断字相关的 js
3. 改 `render_page()`
    - 改 html lang 属性为 "ko"
4. 改 `render_article()`
    - 改前后翻页提示语
    - 改为 Edit on Github，以及对应的地址
