### ISSUE TITLE
配置stdlib

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#5]
Julia源码中的doc会编译然后收集stdlib里的markdown文件到doc目录下，再将读入的module名字交给Documenter。现在中文的doc需要想办法收集stdlib的module。

stdlib的markdown文件可以直接从julia的仓库里拷贝过去，要自动化这个过程可能还是需要在这个repo里将julia添加为submodule

**Comment by Gnimuc** [comment]
@Roger-luo 现在stdlib会出现这个问题: https://travis-ci.org/JuliaCN/JuliaZH.jl/jobs/415062099#L666

**Comment by Gnimuc** [comment]
现在没有重新编译sysimg也还是一样的错误
