### ISSUE TITLE
有没有可能在首页添加编译的时间戳？

### ISSUE THREAD

**Issue by findmyway** [JuliaCN/JuliaZH.jl#51]
我刚发现 http://docs.juliacn.com/latest/ 的自动同步脚本挂了，但其实之前浏览的时候并没有意识到这个问题，有没有可能在首页（header/footer）添加一个时间戳之类的编译信息，这样一眼就可以看到最近更新的时间。

**Comment by Gnimuc** [comment]
不改 Documenter.jl，可以用 `@eval` 捕获时间。
```@eval
using Markdown, Dates
Markdown.parse("last update time: $(now())")
```
