### ISSUE TITLE
损坏的连接

### ISSUE THREAD

**Issue by inkydragon** [JuliaCN/JuliaZH.jl#55]
- [C 接口 · Julia中文文档](http://docs.juliacn.com/latest/base/c/#Base.@cfunction)

> See [manual section on ccall and cfunction usage](http://docs.juliacn.com/latest/base/c/base/@ref%20Calling-C-and-Fortran-Code).
> 
> `http://docs.juliacn.com/latest/base/c/base/@ref%20Calling-C-and-Fortran-Code`

英文文档是好的 [C Interface · The Julia Language](https://docs.julialang.org/en/v1/base/c/#Base.@cfunction)
没有解析？

**Comment by June-6th** [comment]
这个是由 docstring 自动生成的，一旦链接的目标是翻译后的文档就可能损坏链接。在 Base 还有其它这种类型的损坏的链接，我感觉除非直接翻译对应的 docstring，否则这应该就会有

**Comment by Gnimuc** [comment]
是的，把 docstring 里的 @ref 改成中文一致才可以。

**Comment by Roger-luo** [comment]
这个会由Base里面的doc string翻译来解决，相关的issue：#4

讨论：https://github.com/Roger-luo/Localize.jl
