### ISSUE TITLE
翻译中 Julia 的大小写

### ISSUE THREAD

**Issue by stone-zeng** [JuliaCN/JuliaZH.jl#62]
中文翻译中“Julia”一词大小写比较混乱，而英文中都统一为首字母大写的“Julia”。是否需要统一规范一下？

**Comment by Roger-luo** [comment]
是的，这个是transfix里的问题还是需要直接修改这个repo？

**Comment by Roger-luo** [comment]
虽然我感觉直接修改repo可能更方便一些（可以用脚本批量修改）不过transifix里面有什么办法么？

**Comment by Gnimuc** [comment]
大小写混乱应该是有人未遵守翻译指南导致的，Julia 仅在表示语言时需要首字母大写，很多命令行及 REPL 里需要全小写。

**Comment by Gnimuc** [comment]
翻了一下校对过的几章，并没有发现不一致的地方，如果发现其它地方出现错误，请在 Transifex 上直接修改。

**Comment by June-6th** [comment]
在中文文档的主页确实有不统一的情况，更改对应的 doc/src/index.md 文件就可以统一。文档其他部分出现的情况应该比较少，因为「Julia」一词在 Transifex 上已经被设置为术语，即使出现也容易在复核时更正；而命令行或 REPL 中的「Julia」一般翻译时会直接复制对应的字符串，也不容易出现大小写不统一的情况。
