### ISSUE TITLE
Update Google Analytics property tracking id

### ISSUE THREAD

**Issue by findmyway** [JuliaCN/JuliaZH.jl#64]
I just notice that the Google Analytics property tracking id of the Chinese docs is using the same id as Documenter.jl

[tracking id in JuliaZH.jl](https://github.com/JuliaCN/JuliaZH.jl/blob/master/doc/make.jl#L156)

[tracking id in Documenter.jl](https://github.com/JuliaDocs/Documenter.jl/blob/master/docs/make.jl#L14)

@ViralBShah 

Do we need to change it to the same id as [JuliaLang/julia](https://github.com/JuliaLang/julia/blob/master/doc/make.jl#L180) ?

**Comment by ViralBShah** [comment]
I have added you to julialang analytics. Also set up cn.julialang.org. I think we need to set up github pages to serve the gh-pages branch.

**Comment by ViralBShah** [comment]
You can see this property id on google analytics now, but the separate one for cn.julialang.org is:
UA-28835595-9
