### ISSUE TITLE
函数文档

### ISSUE THREAD

**Issue by Heptazhou** [JuliaCN/JuliaZH.jl#66]
希望完成函数文档的替换以进行翻译

**Comment by Roger-luo** [comment]
翻译不是在transfix上么？要替换哪些部分？不是已经翻译完了？

https://docs.juliacn.com/latest/manual/functions/

**Comment by Heptazhou** [comment]
Base部分的函数说明

**Comment by Roger-luo** [comment]
Base部分没有函数的文档啊？没看懂你要啥？不然直接提交PR？

https://github.com/JuliaLang/julia/tree/master/doc/src/base

**Comment by Heptazhou** [comment]
抱歉，不知怎么说比较清楚，Base部分基本像是这样，transifex上也没有实际文本不好翻译
> Core.AbstractArray
Base.AbstractVector
Base.AbstractMatrix
Base.AbstractVecOrMat
Core.Array

**Comment by Roger-luo** [comment]
哦，这是doc string部分目前无法翻译。需要等一系列issue解决才行，我们先主要搞定手册部分。

如果想帮忙可以参考：

- #41 
- https://github.com/JuliaCN/JuliaZH.jl/issues/3
- https://github.com/JuliaCN/JuliaZH.jl/pull/11

**Comment by Heptazhou** [comment]
好的，多谢

**Comment by Gnimuc** [comment]
@Heptazhou 我现在的计划是 完善1.0 manual的翻译 -> 更新Documenter -> tag 1.0 -> 更新Transifex到1.1 -> 加入函数文档的翻译，所以还要等一段时间。有兴趣参与翻译可以加翻译群：https://discourse.juliacn.com/t/topic/277
