### ISSUE TITLE
文档国内镜像失去同步

### ISSUE THREAD

**Issue by Gnimuc** [JuliaCN/JuliaZH.jl#70]
GitHub page是正常的，cc @findmyway @Roger-luo

**Comment by findmyway** [comment]
目前 https://docs.juliacn.com 文档的同步策略是通过crontab每天凌晨3点会自动拉取一次gh-pages分支，我看了下日志，应该没问题。明早我再瞅瞅看

**Comment by Gnimuc** [comment]
哦，那应该是还没到同步时间。
