### ISSUE TITLE
Tag 一个版本先把package注册上？

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#72]
现在大部分的manual都已经翻译完了。pdf啥的也弄好了。刚刚REPL里面的keyword的doc string也修复了。我们tag第一个版本把package注册在METADATA？之后开发起来也更方便，可以

```
dev JuliaZH
```

然后大家也可以自己安装试试。我们可以考虑之后提供一些本地编译的工具，这样方便离线查看文档。

**Comment by Roger-luo** [comment]
Done: https://github.com/JuliaLang/METADATA.jl/pull/21941

**Comment by findmyway** [comment]
@Roger-luo 不小心又触发了两个release，不知道对package有啥影响没：

https://github.com/JuliaLang/METADATA.jl/pull/21979

https://github.com/JuliaLang/METADATA.jl/pull/21973

https://github.com/JuliaLang/METADATA.jl/pull/21941

这些PR是机器人自动创建的，好像没法把 v0.1.0 v0.1.1 close掉

**Comment by Gnimuc** [comment]
可以手动删除release和tag, 下次正常release的时候会自动覆盖。

**Comment by findmyway** [comment]
这样子呀，具体怎么操作？

把v0.1.0，v0.1.1, v0.1.2, v0.1.3都删了，再重新release v0.1.0？

**Comment by Gnimuc** [comment]
是的，这样就会自动retag 0.1.0。

**Comment by Roger-luo** [comment]
你需要修改Project.toml里的版本号与tag一致@findmyway

**Comment by Gnimuc** [comment]
可以直接删除Project.toml里的版本号，避免METADATA进行check，这样每次tag版本的时候就方便了。

**Comment by findmyway** [comment]
@Gnimuc 还可以这样子啊，已经删了

**Comment by Roger-luo** [comment]
已注册。
