### ISSUE TITLE
转移到travis-ci.com

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#75]
travis-ci的GitHub service已经deprecate，我刚刚安装了travis app，不过并没有看到能够immigrate的按钮，显示了这一行字

> The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly. Please read our docs on open source migration to learn more.

有人知道怎么回事么？

**Comment by findmyway** [comment]
直接给客服发邮件问下吧

**Comment by Gnimuc** [comment]
到时候会自动移动，现在用.org就行，改一下README的链接。
