### ISSUE TITLE
手册翻译列表

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#8]
现在使用如下方式翻译：

http://discourse.juliacn.com/t/topic/277/3

~~规则：~~

~~请通过提交一个WIP的PR来认领一个文件进行翻译，在PR的comment里面请索引这个issue，每次提交了一个PR之后再领下一个。~~

~~举个例子，PR的题目格式：~~

~~WIP：翻译 "manual/getting-started.md"~~

~~Tips：~~

~~因为现在这个蛋疼的HTML注释问题，我们需要用Documenter的raw标签来注释，然后大家可以现在编辑器里用 `<!-- -->` 注释然后再之后用编辑器批量添加 ~~

    ```@raw
    <!-- -->
    ```

----

~~然后在comment里索引#8~~

现在请参考 #18 进行翻译，然后最好先来这里回复一下，以免后面contributor里面找不到你名字。

- [x] "manual/getting-started.md",
- [x] "manual/variables.md",
- [x] "manual/integers-and-floating-point-numbers.md",
- [x] "manual/mathematical-operations.md",
- [x] "manual/complex-and-rational-numbers.md",
- [x] "manual/strings.md",
- [x] "manual/functions.md",
- [x] "manual/control-flow.md",
- [x] "manual/variables-and-scoping.md",
- [ ] "manual/types.md",
- [x] "manual/methods.md",
- [x] "manual/constructors.md",
- [ ] "manual/conversion-and-promotion.md",
- [ ] "manual/interfaces.md",
- [ ] "manual/modules.md",
- [x] "manual/documentation.md",
- [x] "manual/metaprogramming.md",
- [x] "manual/arrays.md",
- [ ] "manual/missing.md",
- [ ] "manual/networking-and-streams.md",
- [x] "manual/parallel-computing.md",
- [ ] "manual/running-external-programs.md",
- [x] "manual/calling-c-and-fortran-code.md",
- [x] "manual/handling-operating-system-variation.md",
- [x] "manual/environment-variables.md",
- [x] "manual/embedding.md",
- [ ] "manual/code-loading.md",
- [ ] "manual/profile.md",
- [x] "manual/stacktraces.md",
- [ ] "manual/performance-tips.md",
- [x] "manual/workflow-tips.md",
- [x] "manual/style-guide.md",
- [x] "manual/faq.md",
- [ ] "manual/noteworthy-differences.md",
- [x] "manual/unicode-input.md",

**Comment by stokhos** [comment]
我来翻译这个："manual/mathematical-operations.md",

**Comment by wangnangg** [comment]
我翻译这个manual/metaprogramming.md

**Comment by findmyway** [comment]
翻译这个 manual/style-guide.md

**Comment by Roger-luo** [comment]
@stokhos @wangnangg @findmyway 翻译前注意下，有些可能在老的 https://github.com/JuliaCN/julia_zh_cn 里面已经翻译过了（manual文件夹下有一些markdown文件），但是格式可能不对，无法编译。如果已经有的话直接复制过来，然后提交PR，CI已经开启，所以你们可以看到自己修改的文档是否能够编译。

现在文档使用 Documenter.jl 驱动。

**Comment by honghuzi** [comment]
manul/complex-and-rational-numbers.md

**Comment by honghuzi** [comment]
manul/strings.md

**Comment by Roger-luo** [comment]
@honghuzi 先提PR再翻下一章吧，分开提交清楚一些

**Comment by honghuzi** [comment]
manul/strings.md

**Comment by Roger-luo** [comment]
这里的注释需要在外面加

    ```@raw html
    blabla
    ```

参照一下我已经写好的部分。这是因为目前Julia自带的Markdown parser不支持html comment。需要用这种方式work around一下，我已经给Documenter提了issue了，但是目前只能这么凑合。

**Comment by Tmono** [comment]
我来翻译 "manual/functions.md"

**Comment by woodwm** [comment]
我在transifex上翻译"manual/control-flow.md"，过一段时间就会提交PR。

**Comment by Gnimuc** [comment]
@woodwm 感谢参与翻译工作，目前基于transifex方案我们会自动利用transifex的客户端统一同步并提交PR。

**Comment by woodwm** [comment]
明白，我已经看到论坛里的说明了。"manual/control-flow.md"已经翻译完了。

**Comment by auxetic** [comment]
html注释的样式是不是应该统一成

这样更方便和原始文档做diff。

**Comment by Gnimuc** [comment]
@auxetic 我们现在已经换用transifex作为翻译平台，不需要再加html注释了: http://discourse.juliacn.com/t/topic/98

**Comment by Roger-luo** [comment]
我们已经现在转移到transifex所以我就把这个关了。
