### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by Heptazhou** [JuliaCN/JuliaZH.jl#80]
https://github.com/JuliaCN/JuliaZH.jl/blob/b695192afa7ddc7a7330eaa8e314d2449b731190/src/basedocs.jl#L18 行中“模型”是否为“模式”？

**Comment by Roger-luo** [comment]
这里确实是“模式”，你在哪里看到的模型？

**Comment by Heptazhou** [comment]
https://github.com/JuliaCN/JuliaZH.jl/blob/b695192afa7ddc7a7330eaa8e314d2449b731190/src/basedocs.jl#L18 [readme](https://github.com/JuliaCN/JuliaZH.jl/blob/master/README.md#使用) 以及 repl 中都是

![image](https://user-images.githubusercontent.com/42952940/56191504-fc9c5c80-601b-11e9-8919-4a5bd652cffd.png)
