### ISSUE TITLE
tag 1.1

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#83]
我们在1.2 release前tag一下1.1的文档？我已经给org安装 @JuliaRegisterator 了

**Comment by Gnimuc** [comment]
需要先把Transifex上的source全部更新到1.1-release branch，之前我已经更新了manual的source到1.1，Transifex可能正常检测diff，但目前还没有更新其它的source。

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register
