### ISSUE TITLE
pdf版本似乎编译不成功

### ISSUE THREAD

**Issue by findmyway** [JuliaCN/JuliaZH.jl#85]
不知道为啥，我重新build了一次，pdf版本的文档似乎还是没有生成，看travis上的log挺正常的，等我有空的时候再仔细测试下

**Comment by June-6th** [comment]
我试着编译了一次，基本可以确定是 Makrodwn 中代码块的 `%` 字符导致的，tex 文件编译中断的地方都是有 `%` 字符的代码块，并且环境都是 `minted`。tex 代码出错的格式基本是这样的：

```tex
\begin{minted}[escapeinside=\%\%]{jlcon}
1 %\%% 2
\end{minted}
```

**Comment by findmyway** [comment]
估计是Documenter.jl 的锅，英文的pdf编译也挂了，我去创建个issue

**Comment by June-6th** [comment]
用新版本的 Documenter.jl 可以编译成功了。
