### ISSUE TITLE
https://docs.juliacn.com/上的pdf 404错误

### ISSUE THREAD

**Issue by l1t1** [JuliaCN/JuliaZH.jl#86]
https://raw.githubusercontent.com/JuliaCN/JuliaZH.jl/pdf/dev/Julia%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3.pdf

**Comment by findmyway** [comment]
https://github.com/JuliaCN/JuliaZH.jl/issues/85

**Comment by findmyway** [comment]
最近一直没时间细看这个问题，@June-6th 有啥新的发现么？

**Comment by June-6th** [comment]
我仔细看了一下，发现和 `Documenter` 中的[此函数](https://github.com/JuliaDocs/Documenter.jl/blob/d256bf4a68bfe469a0dd106fb8aa46c7cf1175e3/src/Writers/LaTeXWriter.jl#L405)相关。在 `Documenter` 换默认等宽字体的[提交](https://github.com/JuliaDocs/Documenter.jl/pull/1066)中，启用了 `minted` 环境 `escapeinside` 选项，然后就出问题了。

**Comment by June-6th** [comment]
我在 Documenter 提了个 PR 来修这问题，等 PR 合并之后应该就可以了。
