### ISSUE TITLE
更新到1.3?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/JuliaZH.jl#90]
https://github.com/JuliaCN/JuliaZH.jl/blob/93a8f8841995b809eb8e6781c53fb9a0a05aeb21/.gitlab-ci.yml#L1

我们要不要更新下这个image？到1.3或者1.4

**Comment by Gnimuc** [comment]
不太清楚，这里有什么兼容性问题么？

**Comment by johnnychen94** [comment]
或者直接用 `julia:1-stretch`
